<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Barang;

class BarangSeeder extends Seeder
{
    public function run(): void
    {
        Barang::insert([
            [
                'kode_barang' => 'BRG001',
                'nama_barang' => 'Kaos Polos Hitam',
                'stok' => 25,
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG002',
                'nama_barang' => 'Celana Jeans',
                'stok' => 12,
                'id_kategori' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG003',
                'nama_barang' => 'Jaket Hoodie',
                'stok' => 4,
                'id_kategori' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG004',
                'nama_barang' => 'Kemeja Formal',
                'stok' => 0,
                'id_kategori' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG005',
                'nama_barang' => 'Kalung Fashion',
                'stok' => 18,
                'id_kategori' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG006',
                'nama_barang' => 'Tas Selempang Wanita',
                'stok' => 10,
                'id_kategori' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG007',
                'nama_barang' => 'Dress Floral',
                'stok' => 15,
                'id_kategori' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG008',
                'nama_barang' => 'Rok Plisket',
                'stok' => 20,
                'id_kategori' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG009',
                'nama_barang' => 'Jaket Denim',
                'stok' => 8,
                'id_kategori' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG010',
                'nama_barang' => 'Kemeja Linen',
                'stok' => 11,
                'id_kategori' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG011',
                'nama_barang' => 'Kaos Oversize',
                'stok' => 30,
                'id_kategori' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG012',
                'nama_barang' => 'Jeans Skinny',
                'stok' => 14,
                'id_kategori' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG013',
                'nama_barang' => 'Sandal Casual',
                'stok' => 22,
                'id_kategori' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG014',
                'nama_barang' => 'Topi Baseball',
                'stok' => 17,
                'id_kategori' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG015',
                'nama_barang' => 'Hijab Pashmina',
                'stok' => 35,
                'id_kategori' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG016',
                'nama_barang' => 'Sweater Rajut',
                'stok' => 9,
                'id_kategori' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG017',
                'nama_barang' => 'Blazer Kerja',
                'stok' => 7,
                'id_kategori' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG018',
                'nama_barang' => 'Dompet Kulit',
                'stok' => 13,
                'id_kategori' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG019',
                'nama_barang' => 'Jam Tangan Analog',
                'stok' => 6,
                'id_kategori' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG020',
                'nama_barang' => 'Kacamata Fashion',
                'stok' => 16,
                'id_kategori' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG021',
                'nama_barang' => 'Kaos Putih Basic',
                'stok' => 40,
                'id_kategori' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG022',
                'nama_barang' => 'Celana Chino',
                'stok' => 19,
                'id_kategori' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG023',
                'nama_barang' => 'Cardigan Wanita',
                'stok' => 12,
                'id_kategori' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG024',
                'nama_barang' => 'Sepatu Sneakers',
                'stok' => 5,
                'id_kategori' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG025',
                'nama_barang' => 'Gelang Titanium',
                'stok' => 24,
                'id_kategori' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG026',
                'nama_barang' => 'Tas Ransel',
                'stok' => 14,
                'id_kategori' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG027',
                'nama_barang' => 'Dress Casual',
                'stok' => 8,
                'id_kategori' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG028',
                'nama_barang' => 'Rok Mini',
                'stok' => 11,
                'id_kategori' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG029',
                'nama_barang' => 'Jaket Bomber',
                'stok' => 3,
                'id_kategori' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => 'BRG030',
                'nama_barang' => 'Kemeja Batik',
                'stok' => 21,
                'id_kategori' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}